{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "64bcd342_ed3412ce",
        "filename": "src/ethernet_interface.cpp",
        "patchSetId": 3
      },
      "lineNbr": 65,
      "author": {
        "id": 1000022
      },
      "writtenOn": "2022-11-01T14:13:54Z",
      "side": 1,
      "message": "@william, Intent is to remove the try catch block where the handler of the exception is only logging the error?",
      "range": {
        "startLine": 50,
        "startChar": 0,
        "endLine": 65,
        "endChar": 1
      },
      "revId": "f7ee211d15b345cc2ca2eb100b86f980804b729f",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "ab2b641b_5012f822",
        "filename": "src/system_queries.hpp",
        "patchSetId": 3
      },
      "lineNbr": 4,
      "author": {
        "id": 1000022
      },
      "writtenOn": "2022-11-01T14:13:54Z",
      "side": 1,
      "message": "We have the util file, Are you trying to break this into multiple utils?",
      "range": {
        "startLine": 3,
        "startChar": 0,
        "endLine": 4,
        "endChar": 9
      },
      "revId": "f7ee211d15b345cc2ca2eb100b86f980804b729f",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}